import PLAcceleratedNesterovLean.MorseBott.TubularProjection.Defs
import PLAcceleratedNesterovLean.MorseBott.TubularProjection.IFT
import PLAcceleratedNesterovLean.MorseBott.TubularProjection.Derivative
